version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "phanect"
    groups:
      compatible:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
      # Better Auth frequently makes breaking changes in minor versions,
      # so make different PRs from other version updates.
      better-auth:
        applies-to: "version-updates"
        patterns:
          - "@better-auth/cli"
          - "better-auth"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "phanect"
    groups:
      normal:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "phanect"
