#:schema https://mise.jdx.dev/schema/mise.json

[tools]
node = { version = "24" }
"npm:nushell" = "latest"
python = "3"
pipx = "latest"
"pipx:git+https://github.com/github/spec-kit.git" = "latest"

[tasks]
  [tasks.dev]
  depends = [ "prepare" ]
  run = "next dev --inspect"

  [tasks.start]
  run = "next start"

  [tasks.db]
  run = "psql --username=guildkit --dbname=guildkit --host=localhost --port=5432"

  [tasks.build]
  depends = [ "prepare" ]
  run = "next build"
  env = { NODE_ENV = "production" }

  [tasks.lint]
  depends = [ "prepare" ]
  run = [
    "tsc --noEmit",
    "eslint"
  ]

  [tasks.fix]
  depends = [ "prepare" ]
  run = [
    "eslint --fix",
    "prisma format",
  ]

  [tasks.clean]
  depends = [ "clean:*" ]

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "pnpm install",
    { task = "prepare" },
  ]
  raw = true # Required for the spinner and interactive UIs

  # TODO disabled until GA
  #[tasks.release]
  #run = "npm publish --access public --non-interactive"

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile",
  "mise run prepare",
]

[env]
_.file = ".env"
_.path = "./node_modules/.bin"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
