#!/usr/bin/env -S pnpm exec jiti

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { deduplicate, trimLines } from "@phanect/utils";
import { XMLParser } from "fast-xml-parser";

const projectRoot = join(import.meta.dirname, "../../..");

const generateCurrencyEnum = async () => {
  type SixGroupIsoCurrencyList = {
    ISO_4217: {
      CcyTbl: {
        CcyNtry: {
          CtryNm: string;
          CcyNm: string;
          Ccy: string;
          CcyNbr: string;
          CcyMnrUnts: number;
        }[];
      };
    };
  };

  const res = await fetch("https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml");
  const xmlText = await res.text();
  const xml = new XMLParser().parse(xmlText) as SixGroupIsoCurrencyList;

  const currencyCodes = deduplicate(
    xml.ISO_4217.CcyTbl.CcyNtry.map(({ CtryNm, CcyNm, Ccy }) => ({
      name: CcyNm,
      country: CtryNm,
      code: Ccy,
    })).map((currency) => currency.code)
      .filter((code) => code)
      .sort((codeA, codeB) => codeA > codeB ? 1 : -1)
  );

  const intermediateDirPath = join(projectRoot, "src/intermediate");
  const prismaModelDirPath = join(projectRoot, "prisma/models");

  await Promise.all([
    mkdir(intermediateDirPath, { recursive: true }),
    mkdir(prismaModelDirPath, { recursive: true }),
  ]);

  await Promise.all([
    writeFile(
      join(intermediateDirPath, "currencies.ts"),
      trimLines(`
      // Auto generated by scripts/scripts-sync-currency.ts. DO NOT EDIT MANUALLY.

      export const currencies = ${ JSON.stringify(currencyCodes) } as const;
    `),
    ),
    writeFile(
      join(prismaModelDirPath, "currencies.prisma"),
      trimLines(`
      // Auto generated by a mise task \`setup:currencies\`. DO NOT EDIT MANUALLY.

      enum Currency {
        ${ currencyCodes.join("\n") }
      }
    `),
    ),
  ]);
};

await generateCurrencyEnum();
