#:schema https://mise.jdx.dev/schema/mise.json

[tasks]
  [tasks.dev]
  depends = [ "sync" ]
  run = "next dev --inspect"

  [tasks.start]
  run = "next start"

  [tasks.build]
  depends = [ "sync" ]
  run = "next build"
  env = { NODE_ENV = "production" }

  [tasks.lint]
  depends = [ "sync" ]
  run = "tsc --noEmit"

  [tasks.fix]
  depends = [ "sync" ]
  run = "prisma format"

  # TODO disabled until GA
  #[tasks.publish]
  #run = "npm publish --access public --non-interactive"

  [tasks.sync]
  run = [{ tasks = [ "sync:*" ]}]

  [tasks.setup]
  run = [{ tasks = [ "setup:*" ]}]
  depends_post = "sync"

[env]
_.path = "./node_modules/.bin"
