name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
  release:
    types:
      - published

permissions:
  contents: read

env:
  # On the build process, the credentials for OAuth can be dummy
  GOOGLE_CLIENT_ID: dummy
  GOOGLE_CLIENT_SECRET: dummy
  GITHUB_CLIENT_ID: dummy
  GITHUB_CLIENT_SECRET: dummy

jobs:
  test:
    name: test on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version:
          - 24
    env:
      SERVER_ENV: development
      MISE_NODE_VERSION: ${{ matrix.node-version }} # Override Node.js version over mise.toml
      DATABASE_URL: "postgresql://guildkit:guildkit@localhost:5432/guildkit?sslmode=disable"
      BETTER_AUTH_URL: "http://localhost:3000"
      # On the build process, the credentials can be dummy
      BETTER_AUTH_SECRET: dummy_67Vl2BsxaiKFX41eYaGqvCHHQ4
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: |
          sudo systemctl stop docker
          sudo apt-get remove -y docker

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true

      - run: mise build
      # TODO - run: mise test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SERVER_ENV: development
      DATABASE_URL: "postgresql://guildkit:guildkit@localhost:5432/guildkit?sslmode=disable"
      BETTER_AUTH_URL: "http://localhost:3000"
      # On the build process, the credentials can be dummy
      BETTER_AUTH_SECRET: dummy_67Vl2BsxaiKFX41eYaGqvCHHQ4
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: sudo apt-get remove -y docker

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true

      - run: mise lint

  publish:
    needs:
      - test
      - lint
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: production
      SERVER_ENV: production
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: sudo apt-get remove -y docker

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true

      - run: mise build

      - name: Set npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
      - run: mise release
